apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-delete-file
spec:
  concurrencyPolicy: Forbid
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-delete-file
            image: internxt/photos-delete-files:$GITHUB_SHA
            command:
            - sh
            - -c
            - node bin/delete-photos/index.ts -d $DB_HOST -l $LIMIT -e $ENDPOINT -s $SECRET
          restartPolicy: OnFailure
          imagePullSecrets:
          - name: regcred