version: '3.9'

networks:
  internxt:
    name: internxt

services:
  photos-mongo:
    image: mongo:latest
    container_name: photos-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: photos
    volumes:
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27018:27017
    networks:
      - internxt

  mongo-viewer:
    image: mongo-express
    container_name: mongo-viewer
    restart: always
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@photos-mongo:27017/photos
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    ports:
      - 8081:8081
    depends_on:
      - photos-mongo
    networks:
      - internxt
