name: run-tests
on:
  pull_request:
    branches:
      - 'master'
jobs:
  run-tests:
    runs-on: ubuntu-latest
    environment:
      name: development
    env:
      DATABASE_URI: ${{ secrets.DATABASE_URI }}
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Start MongoDB
        run: docker run -p 27017:27017 -d mongo

      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/

      - run: yarn
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: yarn run lint && yarn run test
